"""
Configuration package
配置包
"""

from .settings import *

__all__ = [
    'PACKAGE_NAME', 'VERSION',
    'ROOT_DIR', 'SRC_DIR', 'RESOURCES_DIR', 'LOG_DIR', 'SAVE_DIR',
    'BOARD_SIZE', 'WIN_LENGTH',
    'DEFAULT_THEME', 'DEFAULT_LANGUAGE',
    'LOG_FORMAT', 'LOG_LEVEL', 'LOG_FILE',
    'WINDOW_SIZE', 'CELL_SIZE', 'PIECE_RADIUS',
    'DEFAULT_HOST', 'DEFAULT_PORT',
    'AI_DIFFICULTY_LEVELS', 'DEFAULT_AI_DIFFICULTY', 'AI_THINKING_TIME',
    'AUTO_SAVE_INTERVAL', 'MAX_AUTO_SAVES', 'MAX_SAVE_FILES', 'SAVE_FILE_FORMAT',
    'INITIAL_RATING', 'K_FACTOR', 'RATING_FLOOR', 'RATING_CHANGES',
    'LEADERBOARD_CATEGORIES', 'LEADERBOARD_LIMIT', 'ACTIVE_DAYS', 'INACTIVE_PENALTY',
    'MAX_SPECTATORS_PER_GAME', 'SPECTATOR_UPDATE_INTERVAL',
    'SPECTATOR_CHAT_ENABLED', 'SPECTATOR_CHAT_HISTORY', 'SPECTATOR_FEATURES'
]
