apiVersion: apps/v1
kind: Deployment
metadata:
  name: gomoku-world
  namespace: games
  labels:
    app: gomoku-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gomoku-world
  template:
    metadata:
      labels:
        app: gomoku-world
    spec:
      containers:
      - name: gomoku-world
        image: gomoku_world:latest
        ports:
        - containerPort: 5000
        env:
        - name: PYTHONPATH
          value: /app/src
        - name: DEBUG
          value: "0"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: config
          mountPath: /app/config
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: config
        configMap:
          name: gomoku-world-config
      - name: logs
        emptyDir: {} 