apiVersion: v1
kind: Service
metadata:
  name: gomoku-world
  namespace: games
  labels:
    app: gomoku-world
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: gomoku-world
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gomoku-world
  namespace: games
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: gomoku.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gomoku-world
            port:
              number: 80 