apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gomoku-world
  namespace: game-systems
spec:
  serviceName: gomoku-world
  replicas: 3
  selector:
    matchLabels:
      app: gomoku-world
  template:
    metadata:
      labels:
        app: gomoku-world
    spec:
      containers:
      - name: game-server
        image: gomoku-world:latest
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 50051
          name: grpc
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: game-data
          mountPath: /data
        env:
        - name: REDIS_HOST
          value: redis-master
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: url
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: game-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi 